### ISSUE TITLE
Crash during the initialization of the SDK after updating from 1.x to 2.3.1

### ISSUE THREAD

**Issue by qonto-android-team** [Futurae-Technologies/android-sdk#3]
Hello,

We are facing a crash in our app after bumping the SDK from version 1.4.1 to version 2.3.1. 
This crash affects an average of 50 users on a base of more than 200k users. All Android devices with all Android versions are impacted.
This crash forbids the users from using the application because we initialize the app during the app's startup. 

Stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to create application : javax.crypto.IllegalBlockSizeException
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7619)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
       
Caused by javax.crypto.IllegalBlockSizeException:
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:619)
       at javax.crypto.Cipher.doFinal(Cipher.java:2056)
       at com.futurae.sdk.g.e.a(:61)
       at com.futurae.sdk.g.i.b(:39)
       at com.futurae.sdk.FuturaeClient.getAccountsStatus(FuturaeClient.java:91)
       at com.futurae.sdk.FuturaeClient.b(FuturaeClient.java:105)
       at com.futurae.sdk.FuturaeSDK.launch(:272)
       at xxx.FuturaeScaClient.init(FuturaeScaClient.java:19)
       at xxx.onCreate(App.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7614)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
 
Caused by android.security.KeyStoreException: Invalid operation handle (internal Keystore code: -28 message: In KeystoreOperation::finish

Caused by:
    0: In finish
    1: In check_active: Call on finalized operation with outcome: Pruned.
    2: Error::Km(ErrorCode(-28)))
       at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:418)
       at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
       at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
       at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:609)
       at javax.crypto.Cipher.doFinal(Cipher.java:2056)
       at com.futurae.sdk.g.e.a(:61)
       at com.futurae.sdk.g.i.b(:39)
       at com.futurae.sdk.FuturaeClient.getAccountsStatus(FuturaeClient.java:91)
       at com.futurae.sdk.FuturaeClient.b(FuturaeClient.java:105)
       at com.futurae.sdk.FuturaeSDK.launch(:272)
       at xxx.FuturaeScaClient.init(FuturaeScaClient.java:19)
       at xxx.App.onCreate(App.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7614)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

We attempted to mitigate the issue by calling the `reset` method of the SDK when an exception is thrown by the `launch`method. 
We are still unclear on what would happen if users receive a notification to confirm the authentication while having corrupted data on Futurae's side.

```kotlin
class FuturaeScaClient @Inject constructor(private val application: Application) : ScaClient {
    override fun init() {
        try {
            FuturaeSDK.INSTANCE.launch(
                application,
                SDKConfiguration.Builder()
                    .setLockConfigurationType(LockConfigurationType.NONE)
                    .build(),
            )
        } catch (generalSecurityException: GeneralSecurityException) {
            throw ScaClient.InitialisationException(generalSecurityException)
        } catch (lockCorruptedStateException: LockCorruptedStateException) {
            throw ScaClient.InitialisationException(lockCorruptedStateException)
        }
    }

    override fun reset() {
        try {
            FuturaeSDK.INSTANCE.reset(application)
        } catch (lockedUnexpectedException: LockUnexpectedException) {
            Logger.e("SCA: Error while resetting Futurae SDK", lockedUnexpectedException)
            throw ScaClient.ResetException(lockedUnexpectedException)
        }
    }
}
```

And then,

```kotlin
class FuturaeScaClientInit @Inject constructor(
    private val scaClient: ScaClient,
) : ScaClientInit {

    override fun init() {
        try {
            initSdk()
        } catch (initialisationException: ScaClient.InitialisationException) {
            Logger.e("SCA: Error while initialising Futurae SDK", initialisationException)
            restartSdk()
        }
    }

    private fun initSdk() {
        scaClient.init()
    }

    private fun restartSdk() {
        resetSdk()
        initSdk()
    }

    private fun resetSdk() {
        scaClient.reset()
    }
}
```

**Comment by dimitrisFuturae** [comment]
Hi @qonto-android-team  and thank you for bringing this to our attention. 

We managed to reproduce this reliably on an older Pixel 3 Device while we weren't able to reproduce it on most of our test devices. From the stracktrace and our tests we see that this happens when a long running flow with multiple operations runs a Keystore operation on a background worker thread. Running the specific operation that throws the error on the main thread fixes the issue for the device. 

You can expect a new minor release with this fix in the upcoming days.

**Comment by qonto-android-team** [comment]
Dear Futurae's team,

The situation has improved with the version 2.3.2 you provided. 

Nevertheless, we are still getting exceptions during the initialization of the SDK. I'm posting the stack traces bellow:

```
Caused by com.futurae.sdk.exception.LockCorruptedStateException: Migration failed
       at com.futurae.sdk.FuturaeSDK.launch(:311)
       at com.app.FuturaeScaClient.init(FuturaeScaClient.java:19)
       at com.app.FuturaeScaClientInit.initSdk(FuturaeScaClientInit.java:2)
       at com.app.FuturaeScaClientInit.init(FuturaeScaClientInit.java)
       at com.app.App.onCreate(App.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7256)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Caused by com.futurae.sdk.exception.LockMigrationFailedException: Migration to SDK unlock failed. Please reset the SDK.
       at com.futurae.sdk.j.a(:132)
       at com.futurae.sdk.FuturaeSDK.launch(:254)
       at com.app.FuturaeScaClient.init(FuturaeScaClient.java:19)
       atcom.app.FuturaeScaClientInit.initSdk(FuturaeScaClientInit.java:2)
       at com.app.FuturaeScaClientInit.init(FuturaeScaClientInit.java)
       at com.app.App.onCreate(App.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7256)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Caused by javax.crypto.BadPaddingException:
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:609)
       at javax.crypto.Cipher.doFinal(Cipher.java:2056)
       at com.futurae.sdk.d.a.a(:22)
       at com.futurae.sdk.e.b.a(:50)
       at com.futurae.sdk.e.a.a(:198)
       at com.futurae.sdk.f.a(:20)
       at com.futurae.sdk.j.a(:27)
       at com.futurae.sdk.FuturaeSDK.launch(:254)
       at com.app.FuturaeScaClient.init(FuturaeScaClient.java:19)
       at com.app.FuturaeScaClientInit.initSdk(FuturaeScaClientInit.java:2)
       at com.app.FuturaeScaClientInit.init(FuturaeScaClientInit.java)
       at com.app.App.onCreate(App.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7256)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Caused by android.security.KeyStoreException: Invalid argument (internal Keystore code: -38 message: In KeystoreOperation::finish

Caused by:
    0: In finish: KeyMint::finish failed.
    1: Error::Km(ErrorCode(-38)))
       at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
       at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
       at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
       at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
       at javax.crypto.Cipher.doFinal(Cipher.java:2056)
       at com.futurae.sdk.d.a.a(:22)
       at com.futurae.sdk.e.b.a(:50)
       at com.futurae.sdk.e.a.a(:198)
       at com.futurae.sdk.f.a(:20)
       at com.futurae.sdk.j.a(:27)
       at com.futurae.sdk.FuturaeSDK.launch(:254)
       at com.app.FuturaeScaClient.init(FuturaeScaClient.java:19)
       at com.app.FuturaeScaClientInit.initSdk(FuturaeScaClientInit.java:2)
       at com.app.FuturaeScaClientInit.init(FuturaeScaClientInit.java)
       at com.app.App.onCreate(App.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7256)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
